export const myProjects = [
  {
    projectTitle: "Mern Stack project",
    desc: "admin-email : abdomosad85@gmail.com",
    title: "E-commerce",
    category: ["bootstrap,mern"],
    imgPath: "e-commerce.png",
    githubLink: "https://github.com/AbdulrahmanMossad/E-commerce-frontend",
    proLink: "https://e-commerce-frontend-bfef2.web.app/",
  },
  {
    projectTitle: "Mern Stack project",
    desc: "real-time chat using socket.io",
    title: "chat-app",
    category: ["tail,mern"],
    imgPath: "chat.png",
    githubLink: "https://github.com/AbdulrahmanMossad/chat-app",
    proLink: "https://chat-app-iduc.onrender.com/",
  },
  {
    projectTitle: "react & tailwind project",
    title: "Golebra",
    desc: "google-authentication , sanity for API .",
    category: ["tail"],
    imgPath: "golebra.png",

    githubLink: "https://github.com/AbdulrahmanMossad/golebra-frontend",
    proLink: "https://golebra-bdad7.web.app/",
  },
  {
    projectTitle: "react-bootstrap project",
    desc: "using The Movie Database website for API.",
    title: "Movies",
    category: ["bootstrap"],
    imgPath: "movies.png",
    githubLink: "https://github.com/AbdulrahmanMossad/Movies",
    proLink: "https://movies-c7ea1.web.app/",
  },
  {
    projectTitle: "react-mui project",
    desc: "React-MaterialUi with static database.",
    title: "Dashboard",
    category: ["react,mui"],
    imgPath: "dashboard.png",
    githubLink: "https://github.com/AbdulrahmanMossad/dashboard",
    proLink: "https://dashboard-c2983.web.app/",
  },
  {
    projectTitle: "react-bootstrap project",
    desc: "React-bootstrap with static database.",
    title: "Menu",
    category: ["bootstrap"],
    imgPath: "menu.png",
    githubLink: "https://github.com/AbdulrahmanMossad/resturant-menu",
    proLink: "https://resturant-menu-ba5ef.web.app/",
  },
  {
    projectTitle: "html-css-js project",
    desc: "simple landing page with html,css and js.",
    title: "landing-page",
    category: ["html"],
    imgPath: "land.png",
    githubLink: "https://github.com/AbdulrahmanMossad/landing-page",
    proLink: "https://landing-page-fa1ef.web.app/",
  },
  {
    projectTitle: "html-css-js project",
    desc: "simple single page project with html , css and js.",
    title: "Html-css-js project",
    category: ["html"],
    imgPath: "html-css.png",
    githubLink: "https://github.com/AbdulrahmanMossad/html-css-project",
    proLink: "https://html-css-project-b73e5.web.app/",
  },
  {
    projectTitle: "Html-css-js project ",
    desc: "simple portfolio with html , css and js.",
    title: "Portfolio",
    category: ["html"],
    imgPath: "portfolio.png",
    githubLink: "https://github.com/AbdulrahmanMossad/portfolio",
    proLink: "https://my-portfolio-3821e.web.app/",
  },
  // {
  //   projectTitle: "html-css project",
  //   category: ["html"],
  //   imgPath: "./images/3.jpg",
  // },
  // {
  //   projectTitle: "react-mui project",
  //   title: "",
  //   category: ["mui"],
  //   imgPath: "./images/4.jpg",
  // },
  // { projectTitle: "mui project", category: ["mui"], imgPath: "./images/5.jpg" },

  // {
  //   projectTitle: "javaScript project",
  //   title: "",
  //   category: ["java"],
  //   imgPath: "./images/6.jpg",
  // },
  // {
  //   projectTitle: "next project",
  //   title: "",
  //   category: ["next"],
  //   imgPath: "./images/7.jpg",
  // },
  // {
  //   projectTitle: "next project using mui",
  //   title: "",
  //   category: ["next,mui"],
  //   imgPath: "./images/8.jpg",
  // },
  // {
  //   projectTitle: "javaScript project",
  //   title: "",
  //   category: ["java"],
  //   imgPath: "./images/9.jpg",
  // },
]
